services:
  postgres:
    image: postgres
    container_name: pantheon-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./bbdd/01_scheme.sql:/docker-entrypoint-initdb.d/01_scheme.sql
      - ./bbdd/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql