auth:
  mock: false
  configurationSettingsId: 1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/management?stringtype=unspecified
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql